# -*- coding: utf-8 -*-
"""Generate on-brand ABSTRACT cover images (no third-party IP, no text) for each story,
so the site ships zero unlicensed/watermarked press photos. Lazo gradients + soft generative
geometry, deterministic per slug. Writes blog/img/cover-<slug>.jpg and signal_covers.py (COVERS)."""
import hashlib, pathlib
from PIL import Image, ImageDraw, ImageFilter
BLOG = pathlib.Path(__file__).resolve().parent / "blog"
IMGDIR = BLOG/"img"; IMGDIR.mkdir(parents=True, exist_ok=True)

LAZO = [(50,191,252),(61,118,232),(96,96,190),(181,92,183),(28,25,86)]  # #32BFFC #3D76E8 #6060BE #B55CB7 #1C1956
PAL = {  # category -> (top, bottom) gradient
 "Experiential":((61,118,232),(96,96,190)),
 "Spatial & AR":((50,191,252),(61,118,232)),
 "CGI & VFX":((96,96,190),(181,92,183)),
 "AI":((28,25,86),(61,118,232)),
 "Gaming":((96,96,190),(28,25,86)),
 "Interactive":((50,191,252),(96,96,190)),
 "Concert visuals":((181,92,183),(61,118,232)),
}
# 12 stories (slug, category) — kept local to avoid an import cycle with signal_content
STORIES = [
 ("hollywood-studio-virtual-production","Experiential"),
 ("consumer-ar-glasses-reservations","Spatial & AR"),
 ("airline-turned-beach-into-brand","Experiential"),
 ("stadium-year-round-attraction","Experiential"),
 ("led-volumes-brand-stages","CGI & VFX"),
 ("backlash-against-ai-presence","AI"),
 ("nvidia-real-time-rendering","AI"),
 ("unreal-engine-gamescom-floor","Gaming"),
 ("game-engines-interactive-worlds","Interactive"),
 ("sphere-live-venue","Concert visuals"),
 ("teamlab-interactive-art","Interactive"),
 ("snap-specs-everyday-ar","Spatial & AR"),
]
W, H = 1280, 860

def lerp(a, b, t): return tuple(int(x+(y-x)*t) for x,y in zip(a,b))

def cover(slug, cat, variant=""):
    top, bot = PAL.get(cat, ((61,118,232),(96,96,190)))
    if variant: top, bot = bot, top   # flip the gradient for the secondary image
    col = Image.new("RGB",(1,H))
    for y in range(H): col.putpixel((0,y), lerp(top,bot,y/H))
    base = col.resize((W,H)).convert("RGB")
    hb = hashlib.md5((slug+variant).encode()).digest()
    def hv(i,m): return hb[i%len(hb)]/255*m
    # soft glowing blobs
    layer = Image.new("RGBA",(W,H),(0,0,0,0)); d = ImageDraw.Draw(layer)
    for i in range(4):
        c = LAZO[hb[i]%len(LAZO)]
        r = int(240+hv(i+4,360))
        cx = int(hv(i*2,1)*W); cy = int(hv(i*2+1,1)*H)
        d.ellipse([cx-r,cy-r,cx+r,cy+r], fill=(c[0],c[1],c[2],150))
    layer = layer.filter(ImageFilter.GaussianBlur(120))
    base = Image.alpha_composite(base.convert("RGBA"), layer)
    # faint concentric "signal" rings, seeded center
    rings = Image.new("RGBA",(W,H),(0,0,0,0)); dr = ImageDraw.Draw(rings)
    rx = int(hv(9,1)*W); ry = int(hv(11,1)*H)
    for k in range(6):
        rr = 70+k*90
        dr.ellipse([rx-rr,ry-rr,rx+rr,ry+rr], outline=(244,243,243,26), width=3)
    rings = rings.filter(ImageFilter.GaussianBlur(1))
    base = Image.alpha_composite(base, rings)
    # subtle top-left sheen
    sheen = Image.new("RGBA",(W,H),(0,0,0,0)); ds = ImageDraw.Draw(sheen)
    ds.ellipse([-400,-500,W//2,H//3], fill=(255,255,255,26)); sheen = sheen.filter(ImageFilter.GaussianBlur(140))
    base = Image.alpha_composite(base, sheen).convert("RGB")
    out = IMGDIR/("cover-%s%s.jpg"%(slug,variant))
    base.save(out, "JPEG", quality=82, optimize=True)
    return "img/cover-%s%s.jpg"%(slug,variant)

def build_all():
    COVERS = {}; COVERS2 = {}
    for slug, cat in STORIES:
        COVERS[slug] = cover(slug, cat)
        COVERS2[slug] = cover(slug, cat, "-b")
        print("cover ->", COVERS[slug], "+ b")
    pathlib.Path("signal_covers.py").write_text(
     "# auto-generated by build_covers.py (on-brand abstract covers, no third-party IP)\nCOVERS = %r\nCOVERS2 = %r\n" % (COVERS, COVERS2),
     encoding="utf-8")
    print("wrote signal_covers.py with", len(COVERS), "covers + secondaries")


# Guardado bajo __main__ para que set_articles.py pueda `from build_covers import cover`
# sin re-ejecutar la generación de las 12 portadas originales (efecto colateral).
if __name__ == "__main__":
    build_all()
