# -*- coding: utf-8 -*-
"""Carril 2 — el SETTER.

Toma articles_live.json (las notas reales que Opus investigó y redactó en el esquema ART) y
las 'setea' al blog: GARANTIZA una portada por nota ('consigue imagen') y escribe
articles_live.py, que signal_content.py fusiona con las 12 originales. Luego se corre el build
normal (build_articles / build_blog_b / build_seo) y las notas aparecen en Latest + página propia.

IMÁGENES ('si no trae imagen la tiene que conseguir'):
  - Por defecto GENERA una portada abstracta de marca por nota (build_covers.cover): determinista,
    sin IP de terceros, y garantiza que TODA nota tenga imagen.
  - Con USE_SOURCE_IMAGES=True intenta primero la og:image real de la fuente y cae a la portada
    generada si falla. (Foto de prensa = IP de terceros; por eso queda como opt-in explícito.)

Uso:
  python set_articles.py            # setea articles_live.json -> articles_live.py (+ portadas)
"""
from __future__ import annotations

import io
import json
import pathlib

from build_covers import cover, IMGDIR

BASE = pathlib.Path(__file__).resolve().parent
LIVE_JSON = BASE / "articles_live.json"
LIVE_PY = BASE / "articles_live.py"

EDITION = 21                                   # las notas curadas de esta tanda
EDITION_DATE = ("02 Aug 2026", "2026-08-02")   # se inyecta en signal_content.DATE[21]
USE_SOURCE_IMAGES = True                       # Jon: usar la imagen real de la fuente (og:image), fallback a portada generada

# Campos del esquema ART que consume signal_content.STORIES
ART_FIELDS = ("slug", "headline", "dek", "focus_keyword", "read_minutes",
              "meta_description", "why", "takeaway", "body")


def _download_optimize(url: str, slug: str, maxw: int = 1280) -> str:
    """Baja una imagen real (og:image), la optimiza y la guarda como portada. Opt-in."""
    import html as _html
    import requests
    from PIL import Image
    url = _html.unescape((url or "").strip())   # og:image URLs suelen traer &amp; en el query
    r = requests.get(url, timeout=20, headers={"User-Agent": "Mozilla/5.0"})
    r.raise_for_status()
    im = Image.open(io.BytesIO(r.content)).convert("RGB")
    if im.width > maxw:
        im = im.resize((maxw, round(im.height * maxw / im.width)), Image.LANCZOS)
    out = IMGDIR / ("cover-%s.jpg" % slug)
    im.save(out, "JPEG", quality=82, optimize=True)
    return "img/cover-%s.jpg" % slug


def ensure_images(slug: str, cat: str, image_url: str | None = None) -> tuple[str, str]:
    """Garantiza portada (tarjeta/OG) + variante -b (hero interno). Devuelve (cover, cover_b)."""
    cover_b = cover(slug, cat, "-b")                 # hero interno: siempre generado, on-brand
    if USE_SOURCE_IMAGES and image_url:
        try:
            return _download_optimize(image_url, slug), cover_b
        except Exception as e:
            print(f"  [img] og:image falló para {slug} ({e}); genero portada de marca.")
    return cover(slug, cat), cover_b


def main() -> int:
    try:
        data = json.load(open(LIVE_JSON, encoding="utf-8"))
    except FileNotFoundError:
        print(f"  No hay {LIVE_JSON.name}; nada que setear (se conserva articles_live.py actual).")
        return 0
    arts = data["articles"] if isinstance(data, dict) else data

    ART_LIVE: dict = {}
    TAX_LIVE: list = []
    COVERS_LIVE: dict = {}
    COVERS2_LIVE: dict = {}
    META_LIVE: dict = {}

    for a in arts:
        slug, cat = a["slug"], a["cat"]
        missing = [f for f in ART_FIELDS if f not in a]
        if missing:
            print(f"  [!] {slug}: faltan campos {missing}; se omite.")
            continue
        c, c2 = ensure_images(slug, cat, a.get("image_url"))
        COVERS_LIVE[slug] = c
        COVERS2_LIVE[slug] = c2
        ART_LIVE[slug] = {k: a[k] for k in ART_FIELDS}
        TAX_LIVE.append((slug, cat, a.get("tokens", ""), a.get("edition", EDITION)))
        META_LIVE[slug] = {"source_url": a.get("source_url", ""),
                           "source_name": a.get("source_name", ""),
                           "date": a.get("date", "")}
        print("set ->", slug, "|", cat, "| cover:", c)

    LIVE_PY.write_text(
        "# auto-generated by set_articles.py — do not hand-edit.\n"
        "EDITION = %r\nEDITION_DATE = %r\n"
        "ART_LIVE = %r\nTAX_LIVE = %r\nCOVERS_LIVE = %r\nCOVERS2_LIVE = %r\nMETA_LIVE = %r\n"
        % (EDITION, EDITION_DATE, ART_LIVE, TAX_LIVE, COVERS_LIVE, COVERS2_LIVE, META_LIVE),
        encoding="utf-8")
    print(f"\nwrote articles_live.py with {len(ART_LIVE)} articles (edition {EDITION}).")
    print("Ahora corre: python build_articles.py && python build_blog_b.py && python build_seo.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
